// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import React from "react";
import { TokenProvider } from "@/app/context/TokenContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Birth and Death Registration System",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <meta charSet="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>Birth and Death Registration System</title>
        </head>
        <body className={inter.className}>
        <TokenProvider>
            <div>
                <Header />
                <main>{children}</main>
                <footer className="bg-gray-800 text-white py-4">
                    <div className="container mx-auto text-center">
                        <p>&copy; {new Date().getFullYear()} Birth and Death Registration System. All rights reserved.</p>
                    </div>
                </footer>
            </div>
        </TokenProvider>
        </body>
        </html>
    );
}
